subsampling:
    CutDetectionSubsampler:
        #cuts_are_clips: True
        args:
            cut_detection_mode: "all"
            framerates: null
            threshold: 11.5
            min_scene_len: 15
    WhisperSubsampler:
        model_name: "large-v2"
        batch_size: 16
        compute_type: "float16"
        is_slurm_task: False

reading:
    yt_args:
        download_size: 360
        download_audio_rate: 44100
        yt_metadata_args:
            writesubtitles:  True
            subtitleslangs: ['en']
            writeautomaticsub: True
            get_info: True
    timeout: 60
    sampler: null

storage:
    number_sample_per_shard: 100
    oom_shard_count: 5
    captions_are_subtitles: False

distribution:
    processes_count: 32
    thread_count: 32
    subjob_size: 10000
    # distributor: "slurm"
    # distributor_args:
    #     partition: "develbooster"
    #     n_nodes: 16
    #     account: "cstdl"
    #     cpus_per_task: 16
    #     job_name: "hd_vila_"
    distributor: "multiprocessing"